### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by InteJason** [SaphieNyako/Quest_Giver#1]
**First Stage:**
1) Fix Capabilities
2) Add the option of Advancement detection and reward
3) Finalize Quest GUI
4) Link Quest Availability with reputation
5) Assign Quest Giving Villager

**Second Stage:**
1) Interactive Dialogue Options
2) Spawn Guilds + NPCs in village

**Third Stage (Launch):**
1) Custom Dialogues that Can Trigger Certain Effects (Lower/Increase Reputation, Trigger Quest, etc)
2) Custom Quest Types (TBD)

**Comment by SaphieNyako** [comment]
Made a TODO list as a Project. 
https://github.com/SaphieNyako/Quest_Giver/projects/1
