### ISSUE TITLE
Guard villagers don't stay and look at you when the quest dialogue is opened

### ISSUE THREAD

**Issue by InteJason** [SaphieNyako/Quest_Giver#14]
Title, they don't stop like the quest villagers do.

Expected Behavior: After opening the dialogue box, they stop and look at until the dialogue box is closed.

**Comment by SaphieNyako** [comment]
This is because they are not programmed like the normal villagers. 
The villagers/questvillagers can have a tradingPlayer, wich will become their focus when set, the guards dont have this option. 

I made the guard lootAt the player.

This will be updated in the next 1.0.1 update

**Comment by InteJason** [comment]
Now the guard villager looks at the player briefly, but doesn't stop moving. It also keeps moving after the quest dialogue is opened. Is there any way we can prevent that?

**Comment by SaphieNyako** [comment]
This will be updated in the next 1.0.1 update
