### ISSUE TITLE
Quest Villagers' exclamation and question marks don't render properly

### ISSUE THREAD

**Issue by InteJason** [SaphieNyako/Quest_Giver#17]
The quest villager still have their exclamation mark after the player accepts the quest and finishes it.

Expected Behavior: The quest giver changes from exclamation mark to question mark when the player accepts the quest. Then after the entire quest-line is finished, the quest villager removes the question mark as well

Video: https://youtu.be/UL16fSH85zs

**Comment by SaphieNyako** [comment]
I can't replicate this issue. 
I need more information. 
Does this happen with the same quests?
