### ISSUE TITLE
Quest Giver Ticking Entity crash

### ISSUE THREAD

**Issue by Pyrael123** [SaphieNyako/Quest_Giver#23]
This is for SettingDust

[crash-2023-06-09_08.35.47-server.txt](https://github.com/SaphieNyako/Quest_Giver/files/11704253/crash-2023-06-09_08.35.47-server.txt)

**Comment by SettingDust** [comment]
well. you shouldn't mark it as for anyone. And the crash seems your morevillagers isn't match the quest giver required

**Comment by SettingDust** [comment]
Need add the more villagers version to the quest giver manifest @SaphieNyako

**Comment by SaphieNyako** [comment]
No I dont cause the mod was made for that specific version.
