### ISSUE TITLE
 [Feature Request]  Make random messages translatable.

### ISSUE THREAD

**Issue by StarskyXIII** [SaphieNyako/Quest_Giver#24]
This will be helpful for players whose native language is not English.

https://github.com/SaphieNyako/Quest_Giver/blob/0434f07ce74c8c86de7f94aa7e6a9528c4c8f120/src/main/java/com/feywild/quest_giver/screen/DisplayQuestScreen.java#L126

https://github.com/SaphieNyako/Quest_Giver/blob/0434f07ce74c8c86de7f94aa7e6a9528c4c8f120/src/main/java/com/feywild/quest_giver/screen/DisplayQuestScreen.java#L137

**Comment by SaphieNyako** [comment]
Currently not working on this mod. I'll leave this open for the future. Or someone has to send in a PR for it.

**Comment by SaphieNyako** [comment]
Thank you for the contribution!
Ill upload the new version with these changes.
