### ISSUE TITLE
Add Quest Availability with reputation

### ISSUE THREAD

**Issue by SaphieNyako** [SaphieNyako/Quest_Giver#4]
Add Quest Availability with reputation

**Comment by SaphieNyako** [comment]
![image](https://user-images.githubusercontent.com/77398437/154067011-e42397be-ac21-4d18-8743-718cb73dca05.png)

**Comment by InteJason** [comment]
Two ways advancements can be included in the quest giver mod:
1) For a quest to be completed, you need to trigger a certain advancement
2) Granting advancement as a reward instead of items when a quest is finished

**Comment by SaphieNyako** [comment]
I

> Two ways advancements can be included in the quest giver mod:
> 
> 1. For a quest to be completed, you need to trigger a certain advancement
> 2. Granting advancement as a reward instead of items when a quest is finished

If it's a reward it will be a custom advancement I presume?

**Comment by InteJason** [comment]
Yes, I can create that with a datapack, or if its a custom quest that we may make in the future, we can add the advancement in the mod as well.
